name: Sycrox

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "sycrox_cmd"

          replace: "sycrox_cmd"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Replace That Dependencies'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: Sycrox

          commit_user_email: poxsisofficial@gmail.com
